# Generated by Django 5.0.6 on 2024-06-15 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('color', models.IntegerField()),
                ('sales', models.FloatField()),
                ('margin', models.FloatField()),
                ('balances', models.FloatField()),
                ('turnover', models.FloatField()),
                ('shops', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('planFact', models.FloatField()),
                ('planDay', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('productLine', models.CharField(max_length=100)),
                ('specialTask', models.CharField(max_length=30)),
                ('checks', models.IntegerField()),
                ('conversion', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ChartSpecialTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('specialTask', models.CharField(max_length=30)),
                ('sales', models.DecimalField(decimal_places=2, max_digits=8)),
                ('planFact', models.FloatField()),
                ('planDay', models.FloatField()),
                ('shops', models.ManyToManyField(to='backendapp.shops')),
            ],
        ),
        migrations.CreateModel(
            name='ChartSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sales', models.DecimalField(decimal_places=2, max_digits=8)),
                ('productLine', models.CharField(max_length=100)),
                ('planFact', models.FloatField()),
                ('planDay', models.FloatField()),
                ('shops', models.ManyToManyField(to='backendapp.shops')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('planFact', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sales', models.DecimalField(decimal_places=2, max_digits=5)),
                ('shops', models.ManyToManyField(to='backendapp.shops')),
            ],
        ),
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('сount', models.IntegerField()),
                ('planFact', models.FloatField()),
                ('APPG', models.FloatField()),
                ('shops', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.shops')),
            ],
        ),
        migrations.CreateModel(
            name='Сhecks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('APPG', models.FloatField()),
                ('checksRoz', models.IntegerField()),
                ('checksEcom', models.IntegerField()),
                ('averageСheck', models.FloatField()),
                ('shops', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.shops')),
            ],
        ),
    ]
