# Generated by Django 5.0.6 on 2024-06-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0002_remove_shops_checks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shops_old',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('productLine', models.CharField(max_length=100)),
                ('specialTask', models.CharField(max_length=30)),
                ('conversion', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='shops',
            name='conversion',
        ),
        migrations.RemoveField(
            model_name='shops',
            name='productLine',
        ),
        migrations.RemoveField(
            model_name='shops',
            name='specialTask',
        ),
    ]
