# Generated by Django 5.0.6 on 2024-06-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0004_rename_сount_traffic_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traffic',
            name='APPG',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='traffic',
            name='planFact',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
