# Generated by Django 5.0.6 on 2024-06-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0005_alter_traffic_appg_alter_traffic_planfact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='сhecks',
            name='averageСheck',
        ),
        migrations.AddField(
            model_name='сhecks',
            name='partСheckRoz',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='сhecks',
            name='APPG',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
