# Generated by Django 5.0.6 on 2024-06-15 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0006_remove_сhecks_averageсheck_сhecks_partсheckroz_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='сhecks',
            old_name='partСheckRoz',
            new_name='partCheckRoz',
        ),
    ]
