# Generated by Django 5.0.6 on 2024-06-15 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0007_rename_partсheckroz_сhecks_partcheckroz'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Сhecks',
            new_name='Checks',
        ),
    ]
