# Generated by Django 5.0.6 on 2024-06-15 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0009_conversion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialtask',
            name='sales',
        ),
    ]
