# Generated by Django 5.0.6 on 2024-06-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0010_remove_specialtask_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialtask',
            name='shops',
            field=models.ManyToManyField(related_name='special_tasks', to='backendapp.shops'),
        ),
    ]
