# Generated by Django 5.0.6 on 2024-06-15 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0012_remove_specialtask_shops_specialtask_old_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productline',
            name='date',
        ),
        migrations.RemoveField(
            model_name='productline',
            name='planDay',
        ),
        migrations.RemoveField(
            model_name='productline',
            name='sales',
        ),
        migrations.AlterField(
            model_name='chartsales',
            name='planDay',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='productline',
            name='balances',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='productline',
            name='margin',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='productline',
            name='planFact',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='productline',
            name='shops',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.shops'),
        ),
        migrations.AlterField(
            model_name='productline',
            name='turnover',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.DeleteModel(
            name='SpecialTask_old',
        ),
    ]
