# Generated by Django 5.0.6 on 2024-06-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0013_remove_productline_date_remove_productline_planday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productline',
            name='balancesName',
            field=models.CharField(default='НЦ', max_length=2),
        ),
        migrations.AddField(
            model_name='productline',
            name='colorName',
            field=models.CharField(default='3', max_length=1),
        ),
        migrations.AddField(
            model_name='productline',
            name='marginName',
            field=models.CharField(default='ОС', max_length=2),
        ),
        migrations.AddField(
            model_name='productline',
            name='planFactName',
            field=models.CharField(default='ПР', max_length=2),
        ),
        migrations.AddField(
            model_name='productline',
            name='turnoverName',
            field=models.CharField(default='ОБ', max_length=2),
        ),
    ]
