# Generated by Django 5.0.6 on 2024-06-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0015_alter_chartsales_planfact_remove_chartsales_shops_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartsales',
            name='sales',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
