# Generated by Django 5.0.6 on 2024-06-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0016_alter_chartsales_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartsales',
            name='planFact',
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
    ]
