# Generated by Django 5.0.6 on 2024-06-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0019_alter_chartsales_planfact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartsales',
            name='planFact',
            field=models.DecimalField(decimal_places=4, max_digits=5),
        ),
        migrations.AlterField(
            model_name='chartsales',
            name='sales',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
