# Generated by Django 5.0.6 on 2024-06-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0022_alter_chartsales_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartsales',
            name='planDay',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
