# Generated by Django 5.0.6 on 2024-06-16 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0023_alter_chartsales_planday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartsales',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
