# Generated by Django 5.0.6 on 2024-06-16 07:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0025_alter_chartsales_productline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartspecialtask',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='chartspecialtask',
            name='planDay',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='chartspecialtask',
            name='planFact',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='chartspecialtask',
            name='sales',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.RemoveField(
            model_name='chartspecialtask',
            name='shops',
        ),
        migrations.AddField(
            model_name='chartspecialtask',
            name='shops',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backendapp.shops'),
            preserve_default=False,
        ),
    ]
