# Generated by Django 5.0.6 on 2024-06-16 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0026_alter_chartspecialtask_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shops_old',
        ),
    ]
