# Generated by Django 5.0.6 on 2024-06-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0028_alter_conversion_conversionfact'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.IntegerField()),
                ('colorPROD', models.IntegerField()),
                ('planFactMI', models.DecimalField(decimal_places=2, max_digits=5)),
                ('colorNAC', models.IntegerField()),
                ('marginMI', models.DecimalField(decimal_places=2, max_digits=5)),
                ('colorOST', models.IntegerField()),
                ('balancesMI', models.DecimalField(decimal_places=2, max_digits=5)),
                ('colorOBOR', models.IntegerField()),
                ('turnoverMI', models.DecimalField(decimal_places=2, max_digits=5)),
                ('colorSPEC', models.IntegerField()),
                ('colorTRAFF', models.IntegerField()),
                ('colorCHECK', models.IntegerField()),
                ('colorCONF', models.IntegerField()),
            ],
        ),
    ]
