# Generated by Django 5.0.6 on 2024-06-17 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0029_mainindicator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainindicator',
            old_name='color',
            new_name='color_value',
        ),
    ]
